---
output: html_document
params:
  version: 1.0
---

# Systems of Equations (Differential and Algebraic) 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This week, we will be focusing on Systems of Equations in R. Please review the following readings to refresh your linear algebra skills. 

## This week's prep:
(Also found on Week 13 Canvas page)

### Required reading:

# Systems of Equations

1. Primer - Linear Algebra can be performed easily by computers, but we need to remind ourselves of how to set up problems as a set of matrices before we can so    <https://drive.google.com/file/d/132NvRrMVbBYNex5iNhoeBwC1ck5MZMAB/view?usp=sharing> 

2. Matrix Algebra Overview - basics, notation, refresher on matrix multiplication, using inverse (e.g. eq 8.7), and converting equations to matrix form (section 8.1.3)
<https://drive.google.com/file/d/132NvRrMVbBYNex5iNhoeBwC1ck5MZMAB/view?usp=sharing>

3. Matrix operations in R - 
<https://www.tutorialkart.com/r-tutorial/r-matrix/>

### Optional resources: 
(these materials will be reviewed in class, but are here if you want to get a head start)

1. Matrix overview slides - <https://docs.google.com/presentation/d/1Dp0XE1iyCFbnKjpW4kCnsMJ9ldn0cEAL>

# Differential Equations

Watch this video: <https://www.youtube.com/watch?v=Em339AlejIs> 
